services:
  - type: web
    name: Braids-Bymoon
    env: python
   
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application


    envVars:
      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: braidsbymoon-db
          property: connectionString

      - key: CLOUDINARY_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

databases:
  - name: braidsbymoon-db
    plan: free
    region: oregon
