services:
  - type: web
    name: Braids-Bymoon
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"

      # DATABASE_URL será preenchida automaticamente após criar o banco abaixo
      - key: DATABASE_URL
        fromDatabase:
          name: braidsbymoon-db
          property: connectionString

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      # Django secret
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: braidsbymoon-db
    plan: free
    region: oregon
